server:
  port: 8009

spring:
  cloud:
    config:
      server:
        svn:
          uri: https://terllm-wh/svn/cloud/
          username: terllm
          password: 123456
        default-label: param
  profiles:
    active: subversion
  application:
    name: spring-cloud-config-svn-server