spring:
   mvc:
       static-path-pattern: /*
       view:
           prefix: /pages/  
           suffix: .html  
   resources:
      static-locations:classpath:/static/
   application:
       name: spring-cloud-producer
   zipkin:
       base-url: http://localhost:9001
   sleuth:
       sampler:
         percentage: 1.0
         
server: 
  port: 8002
 # context-path: /produce
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8000/eureka/

  