server:
  port: 8006
spring:
  application:
    name: spring-cloud-config-server
#  profiles:
#    active: native   
#  cloud:
#    config:
#       server:
#         native:
#             search-locations: file:E:\properties\

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Terllm/cloud # 配置git仓库的地址
          search-paths:        # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                # git仓库的账号
          password:  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址      
